### ISSUE TITLE
Privacy is not a marketing argument

### ISSUE THREAD

**Issue by TheFrenchGhosty** [OkunaOrg/okuna-www#120]
So what do we have on the first page on your website : 

"We're sorry but the website doesn't work without JavaScript enabled. Please enable it to continue."

Oh wait, yes JS I forgot it ! This amazing piece of technology that is always so good for privacy.

Ok here we go !

Privacy ! Nice I love privacy

![privacyyyyyy](https://user-images.githubusercontent.com/47571719/62749374-b300d300-ba4b-11e9-86b1-cf2c6bc03b35.png)

Oh a share button !

![share](https://user-images.githubusercontent.com/47571719/62749477-1a1e8780-ba4c-11e9-97f6-37f6ff3d5fc9.png)

I gonna share that with my friends on this amazing privacy social network named facebook ! They're gonna love it ! I mean facebook is really the best place on internet... to get peoples data !

Let's read the privacy policy now !

iubenda.com great ! You don't even control what they do with people that read your privacy policy ! It's so privacy friendly !

So what's in this privacy policy ? 
![mmh privacyyyy](https://user-images.githubusercontent.com/47571719/62749523-4b975300-ba4c-11e9-8c14-90d5d49f3489.png)

Oh Sentry I haven't seen you in a while ! 
Cloudflare ! I missed you so much since the last website I visited !
Google ! Oh you recaptcha are so amazing tracking where I click !

Let's see where it's hosted now !

$ ping okuna.io
PING okuna.io (52.84.198.6) 56(84) bytes of data.

$ whois 52.84.198.6
Organization:   Amazon Technologies Inc. (AT-88-Z)

Amazon ! I love you so much ! You treat your employees so nicely ! And Alexa, such a great device to record people life !

Ok. You understand my point ? Privacy is not a marketing argument, the only "privacy focussed" thing on this website is the fact that your "share" button don't load things from facebook.

"We're Okuna, an ethical social network for a brighter tomorrow." : Start by being ethical on your marketing.

**Comment by lifenautjoe** [comment]
I'm sorry but I fail to see where are we tracking or monitoring your activity 🤔 . 

In regards to the Google recaptcha, its also not loaded on the website by default and we encourage sending an e-mail instead.

https://github.com/OkunaOrg/okuna-www/blob/84ba81dc85f9373f7d44bde5250095e7cf2b8d9e/src/views/contact-us/components/message.vue#L198

<img width="779" alt="image" src="https://user-images.githubusercontent.com/12737509/62776905-276b5e80-baac-11e9-8920-e1cc26df72e4.png">

The website is completely static and hosted in an S3 bucket replicated through Cloudflare.

The application and all of its assets are not. They're all land-locked to the Frankfurt region, place where AWS is subject to one of the best national and pan-european privacy laws.

Choosing AWS in Germany over hosting our own servers or another company was a careful evaluation of both physical and digital security, legal compliance, costs and the smallest amount of time possible in non-moving the project forward.

Sentry we've got our own instance setup and we're making the switch in the upcoming week.

Starting with that one allowed us to focus on fixing the errors that it captured instead of spending the 2 weeks we now have when we launched and with a couple hours to spare per day and where the project would have died if we would have done so.

On a personal beliefs on this, I'm convinced that pragmatism is what's needed to move anything forward, specially for project trying to take on an industry of 800 billion dollars.

The traditional tin-foil approach to everything will leave you stuck 20 years in the past while the actual problem remains unsolved.


P.S. Talking about privacy, you might consider setting up an SSL certificate on your website https://thefrenchghosty.xyz/en.html .

We can provide some assistance on it and some other security headers if you're interested.


<img width="929" alt="image" src="https://user-images.githubusercontent.com/12737509/62777643-613d6480-baae-11e9-977d-7ca29d78d264.png">

<img width="888" alt="image" src="https://user-images.githubusercontent.com/12737509/62777654-6c909000-baae-11e9-960c-ec6e3ec78c40.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/12737509/62777669-74e8cb00-baae-11e9-90cd-230b364e9caa.png">

Cheers! 🍻
